## File generated by the BNF Converter (bnfc 2.9.4.1).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : interpreter

# Rules for building the parser.

Cimex/Abs.hs Cimex/Layout.hs Cimex/Lex.x Cimex/Par.y Cimex/Print.hs Cimex/Test.hs : Cimex.cf
	/home/students/inf/PUBLIC/MRJP/bin/bnfc --haskell -d --functor Cimex.cf || bnfc --haskell -d --functor Cimex.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

interpreter : Cimex/Abs.hs Cimex/Layout.hs Cimex/Lex.hs Cimex/Par.hs Cimex/Print.hs Main.hs
	${GHC} ${GHC_OPTS} Main.hs -o $@

# Rules for cleaning generated files.

clean :
	-rm -f Cimex/*.hi Cimex/*.o Cimex/*.log Cimex/*.aux Cimex/*.dvi *.hi *.o

distclean : clean
	-rm -f interpreter Cimex/Abs.hs Cimex/Abs.hs.bak Cimex/ComposOp.hs Cimex/ComposOp.hs.bak Cimex/Doc.txt Cimex/Doc.txt.bak Cimex/ErrM.hs Cimex/ErrM.hs.bak Cimex/Layout.hs Cimex/Layout.hs.bak Cimex/Lex.x Cimex/Lex.x.bak Cimex/Par.y Cimex/Par.y.bak Cimex/Print.hs Cimex/Print.hs.bak Cimex/Skel.hs Cimex/Skel.hs.bak Cimex/Test.hs Cimex/Test.hs.bak Cimex/XML.hs Cimex/XML.hs.bak Cimex/AST.agda Cimex/AST.agda.bak Cimex/Parser.agda Cimex/Parser.agda.bak Cimex/IOLib.agda Cimex/IOLib.agda.bak Cimex/Main.agda Cimex/Main.agda.bak Cimex/Cimex.dtd Cimex/Cimex.dtd.bak Cimex/Test Cimex/Lex.hs Cimex/Par.hs Cimex/Par.info Cimex/ParData.hs
	-rmdir -p Cimex/

# EOF
